

heartbeat:
  port: 8002
  region: "北京"
  duration: 3
  resources: 5
  grpcHost:


http:
  address: "0.0.0.0:8002"
  port: 8002
  readTimeout: 5000
  writeTimeout: 5000
  noDefaultUserAgentHeader: true
  maxConnPerHost: 10000
  MaxIdleConnDuration: 5000
  NoDefaultUserAgentHeader: 30000

reportRedis:
  address:
  password:
  db: 0


redis:
  address:
  password:
  db: 0

kafka:
  address:
  topIc: "report"


mongo:
  db:
  user:
  password:
  stressDebugTable: "stress_debug"
  sceneDebugTable: "scene_debug"
  apiDebugTable: "api_debug"
  debugTable: "debug_status"
  address:


oss:
  endpoint:
  accessKeyID:
  accessKeySecret:
  bucket:
  split:
  down:

machine:
  maxGoroutines: 20005
  serverType: 1
  netName: ""
  diskName: ""


log:
  path: "/data/logs/RunnerGo/RunnerGo-engine-info.log"


management:
  address: