- name: deploy apipost project
  hosts: all
  vars:
    backup_path: /data/backup
  tasks:
    - name: register variable
      shell: date "+%F_%H-%M-%S"
      register: bak_var
    - name: 创建项目目录
      file: path={{ deploy_path }}/{{ project_name }}  state=directory 
    - name: 创建项目备份目录
      file: path={{ backup_path  }}/{{ project_name }}  state=directory 
    - name: backup file
      archive: path={{ deploy_path }}/{{ project_name }} dest={{ backup_path  }}/{{ project_name }}/{{ project_name }}_{{ bak_var.stdout }}.tar.gz
      when: backfile == 'true'
    - name: updata project
      synchronize:
        src: "{{ WORKSPACE  }}"
        dest: "{{ deploy_path }}/{{ project_name }}/"
    - name: modify config
      synchronize: 
        src: "{{ config  }}"
        dest: "{{ deploy_path }}/{{ project_name }}/"
    - name: modfiy authority
      file: dest={{ deploy_path }}/{{ project_name }}/{{ appname }}  mode=777   group=api owner=api
    - name: modfiy authority group
      file: dest={{ deploy_path }}/{{ project_name }}   recurse=yes  group=api owner=api 
    - name: restart service
      systemd:
          name: "{{ appname }}"
          state: restarted
          daemon_reload: yes
    - name: "检查端口号"
      shell:   ss -ntlp |grep {{ appname }}  | tr ":" " " | awk '{print $5}'
      register: hosts
      until: hosts.stdout == item
      retries: 5
      delay: 5
      with_items: 
        - "8002"