package tools

import (
	"fmt"
	"testing"
)

func TestBase64DeEncode(t *testing.T) {
	str := "ew0KICChsXBsYW5JZKGwIDogMTIzLA0KICAicGxhbk5hbWUiIDogIrLiytTIzs7xIiwNCiAgInRhc2siIDogew0KICAgIKGxdGFza1R5cGWhsCA6IDAsDQogICAgImRpc3RyaWJ1dGVkIiA6IHRydWUsDQogICAgIm1hY2hpbmVzIiA6IFsNCiAgICAgIHsNCiAgICAgICAgImlwIiA6ICIiLA0KICAgICAgICAiYXJlYSIgOiAiIiwNCiAgICAgICAgIndlaWdodCIgOiA4MA0KICAgICAgfSwNCiAgICAgIHsNCiAgICAgICAgImlwIiA6ICIiLA0KICAgICAgICAiYXJlYSIgOiAiIiwNCiAgICAgICAgIndlaWdodCIgOiAyMA0KICAgICAgfQ0KICAgIF0sDQogICAgInRlc3RNb2RlbCIgOiB7DQogICAgInR5cGUiIDogImNvbmN1cnJlbnQiLA0KICAgICAgImNvbmN1cnJlbnRVc2VyIiA6IDEwMDAsDQogICAgICAiZHVyYXRpb24iOiB0cnVlLA0KICAgICAgInJvdW5kcyI6IGZhbHNlLA0KICAgICAgIm51bWJlciI6IDMwMDAsDQogICAgICAidGhyZXNob2xkIjogMzAwLA0KICAgICAgInN0YXJ0Q29uY3VycmVudCI6IDUwLA0KICAgICAgImxlbmd0aCI6IDIwLA0KICAgICAgImxlbmd0aEludGVydmFsIjogNjAsDQogICAgICAiTWF4Q29uY3VycmVudCI6IDEwMDAsDQogICAgICAiZHVyYXRpb24iOiA2MDAsDQogICAgICAiZ3VpZGVsaW5lcyI6IDAsDQogICAgICAidGhyZXNob2xkIjogMzAwLA0KICAgICAgICJlcnJvcnMiOiAwLjAxDQogICAgfQ0KICB9IA0KICAic2NlbnMiICA6IFsNCiAgICB7DQogICAgICAgICJzY2VuSWQiIDogMTIzLA0KICAgICAgICAic2Nlbk5hbWUiIDogIrLiytSzob6wIiwNCiAgICAgICAgImNvbmZpZ3VyYXRpb24iIDogew0KICAgICAgICAgIA0KICAgICAgICB9DQogICAgICAgIA0KICAgIH0NCiAgDQogIA0KICBdDQoNCg0KDQp9"
	_, str = Base64DeEncode(str, "file")
	//abc, err := base64.StdEncoding.DecodeString(str)
	//if err != nil {
	//	fmt.Println(err)
	//}
	//fmt.Println(string(code))
	fmt.Println(str)

	//str = Base64Encode("Hello world, 你好, 世界")
	//fmt.Println(str)
	//
	//code = Base64DeEncode(str, "")
	//fmt.Println(string(code))
}
